(package
  :name "linux-lts"
  :version "6.18.44"
  :synopsis "Longterm Linux kernel"
  :description "Longterm Linux kernel."
  :homepage "https://kernel.org/"
  :license "GPL-2.0-only"
  :libc :any
  :system "x86_64-linux"
  :source {:type :url
           :url "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.18.44.tar.xz"
           :hash "sha256:0f72d938f06828e82c90405174fe572287db7bfe089e2fc46572a99a7f240d43"}
  :dependencies []
  :build-inputs []
  :bootstrap true
  :build {
    :configure [
      ["make" "defconfig"]
      ["scripts/config" "--enable" "BLK_DEV_INITRD"]
      ["scripts/config" "--enable" "DEVTMPFS"]
      ["scripts/config" "--enable" "DEVTMPFS_MOUNT"]
      ["scripts/config" "--enable" "TMPFS"]
      ["scripts/config" "--enable" "PROC_FS"]
      ["scripts/config" "--enable" "SYSFS"]
      ["scripts/config" "--enable" "BINFMT_SCRIPT"]
      ["scripts/config" "--enable" "EXT2_FS"]
      ["scripts/config" "--enable" "EXT4_FS"]
      ["scripts/config" "--enable" "BTRFS_FS"]
      ["scripts/config" "--enable" "VFAT_FS"]
      ["scripts/config" "--enable" "FAT_FS"]
      ["scripts/config" "--enable" "ISO9660_FS"]
      ["scripts/config" "--enable" "JOLIET"]
      ["scripts/config" "--enable" "CDROM"]
      ["scripts/config" "--enable" "BLK_DEV_SR"]
      ["scripts/config" "--enable" "ATA"]
      ["scripts/config" "--enable" "ATA_PIIX"]
      ["scripts/config" "--enable" "NVME_CORE"]
      ["scripts/config" "--enable" "BLK_DEV_NVME"]
      ["scripts/config" "--enable" "SATA_AHCI"]
      ["scripts/config" "--enable" "SCSI"]
      ["scripts/config" "--enable" "BLK_DEV_SD"]
      ["scripts/config" "--enable" "VIRTIO"]
      ["scripts/config" "--enable" "VIRTIO_PCI"]
      ["scripts/config" "--enable" "VIRTIO_BLK"]
      ["scripts/config" "--enable" "VIRTIO_NET"]
      ["scripts/config" "--enable" "VIRTIO_SCSI"]
      ["scripts/config" "--module" "DRM_VIRTIO_GPU"]
      ["scripts/config" "--enable" "USB_SUPPORT"]
      ["scripts/config" "--enable" "USB_XHCI_HCD"]
      ["scripts/config" "--enable" "USB_EHCI_HCD"]
      ["scripts/config" "--enable" "USB_STORAGE"]
      ["scripts/config" "--enable" "USB_UAS"]
      ["scripts/config" "--enable" "MMC"]
      ["scripts/config" "--enable" "MMC_BLOCK"]
      ["scripts/config" "--enable" "MMC_SDHCI"]
      ["scripts/config" "--enable" "MMC_SDHCI_PCI"]
      ["scripts/config" "--enable" "HID_GENERIC"]
      ["scripts/config" "--enable" "USB_HID"]
      ["scripts/config" "--enable" "SERIO"]
      ["scripts/config" "--enable" "SERIO_I8042"]
      ["scripts/config" "--enable" "KEYBOARD_ATKBD"]
      ["scripts/config" "--enable" "MOUSE_PS2"]
      ["scripts/config" "--module" "HID_MULTITOUCH"]
      ["scripts/config" "--enable" "I2C"]
      ["scripts/config" "--module" "I2C_HID_ACPI"]
      ["scripts/config" "--enable" "SERIAL_8250"]
      ["scripts/config" "--enable" "SERIAL_8250_CONSOLE"]
      ["scripts/config" "--enable" "DRM"]
      ["scripts/config" "--enable" "DRM_KMS_HELPER"]
      ["scripts/config" "--enable" "DRM_FBDEV_EMULATION"]
      ["scripts/config" "--enable" "DRM_SIMPLEDRM"]
      ["scripts/config" "--module" "DRM_I915"]
      ["scripts/config" "--module" "DRM_AMDGPU"]
      ["scripts/config" "--module" "DRM_NOUVEAU"]
      ["scripts/config" "--enable" "FB"]
      ["scripts/config" "--enable" "INPUT_EVDEV"]
      ["scripts/config" "--enable" "SND"]
      ["scripts/config" "--module" "SND_HDA_INTEL"]
      ["scripts/config" "--module" "SND_USB_AUDIO"]
      ["scripts/config" "--enable" "SND_HDA_CODEC_HDMI"]
      ["scripts/config" "--module" "SND_SOC"]
      ["scripts/config" "--module" "SND_SOC_SOF"]
      ["scripts/config" "--module" "SND_SOC_SOF_PCI"]
      ["scripts/config" "--enable" "WLAN"]
      ["scripts/config" "--enable" "CFG80211"]
      ["scripts/config" "--enable" "MAC80211"]
      ["scripts/config" "--module" "IWLWIFI"]
      ["scripts/config" "--module" "IWLMVM"]
      ["scripts/config" "--module" "ATH9K"]
      ["scripts/config" "--module" "ATH10K_PCI"]
      ["scripts/config" "--module" "ATH11K_PCI"]
      ["scripts/config" "--module" "BRCMFMAC"]
      ["scripts/config" "--module" "RTW88"]
      ["scripts/config" "--module" "RTW88_8822BE"]
      ["scripts/config" "--module" "RTW89"]
      ["scripts/config" "--module" "MT76"]
      ["scripts/config" "--module" "MT7921E"]
      ["scripts/config" "--enable" "BT"]
      ["scripts/config" "--module" "BT_RFCOMM"]
      ["scripts/config" "--module" "BT_HIDP"]
      ["scripts/config" "--module" "BT_HCIBTUSB"]
      ["scripts/config" "--module" "R8169"]
      ["scripts/config" "--module" "E1000E"]
      ["scripts/config" "--module" "IGB"]
      ["scripts/config" "--module" "IGC"]
      ["scripts/config" "--module" "ATLANTIC"]
      ["scripts/config" "--module" "BNXT"]
      ["scripts/config" "--module" "FUSE_FS"]
      ["scripts/config" "--module" "OVERLAY_FS"]
      ["scripts/config" "--module" "SQUASHFS"]
      ["scripts/config" "--enable" "EFI"]
      ["scripts/config" "--enable" "EFI_STUB"]
      ["scripts/config" "--enable" "EFIVAR_FS"]
      ["scripts/config" "--disable" "DEBUG_INFO_BTF"]
      ["scripts/config" "--disable" "STACK_VALIDATION"]
      ["scripts/config" "--disable" "UNWINDER_ORC"]
      ["scripts/config" "--enable" "UNWINDER_FRAME_POINTER"]
      ["scripts/config" "--enable" "MODULES"]
      ["scripts/config" "--set-str" "SYSTEM_TRUSTED_KEYS" ""]
      ["scripts/config" "--set-str" "SYSTEM_REVOCATION_KEYS" ""]
      ["make" "olddefconfig"]
    ]
    :build [["make" "-j$CPUS" "bzImage" "modules"]]
    :install [
      ["mkdir" "-p" "$out/lib/radix/kernel" "$out/lib/modules"]
      ["cp" "arch/x86/boot/bzImage" "$out/lib/radix/kernel/vmlinuz"]
      ["cp" ".config" "$out/lib/radix/kernel/config"]
      ["make" "INSTALL_MOD_PATH=$out" "modules_install"]
    ]
  })
